### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by akien-mga** [Nooskewl/monster-rpg-2#1]
Hi there and thanks for making Monster RPG 2 open source! I've finally got around to building allegro 5.1 so I can start enjoying this nice game :)

I have a question about the license and redistribution rights for Monster RPG 2 (as I'd like to package it for Mageia).

The code license seems to be zlib, but there are also two files (FamilyLicense.txt and FreewareLicense.txt) which seem to restrict the rights provided by the zlib license. Could you clarify (maybe in the README.md) whether those restrictions are still valid, and in which context they apply?

Also, which license applies to the contents of the data folder? Are they also under the zlib license, or any other non-code-specific license like CC BY(-SA)?

**Comment by trentg** [comment]
Those licenses (FamilyLicense.txt and FreewareLicense.txt) apply only to the binaries we distribute. Everything else including the data is zlib licensed. You may create binaries and license them any way that complies with zlib.

**Comment by trentg** [comment]
Added this information to the README. Thank you!
