### ISSUE TITLE
Switch all text files to Unix-like line endings

### ISSUE THREAD

**Issue by akien-mga** [Nooskewl/monster-rpg-2#2]
As the title says. Unix-like line endings seem to be the norm for cross-platform code. If you prefer to keep the DOS-like line endings though, it's your call :)

**Comment by akien-mga** [comment]
Note that if you select a given type a line endings to use throughout the repo, you can then force it using .gitattributes: https://github.com/OpenDungeons/OpenDungeons/blob/development/.gitattributes

**Comment by trentg** [comment]
I don't see any point in re-committing practically the whole repo (modify each line) just because it's "the norm". There's no actual benefit from it.

**Comment by akien-mga** [comment]
Ok, then I'll try to use Kate instead of Nano when working on patches, to avoid inserting LF line endings among the CRLF ones :)
