### ISSUE TITLE
How to compile on a Mac?

### ISSUE THREAD

**Issue by VladMarius** [Nooskewl/monster-rpg-2#4]
Hello, i'm trying to compile on a Mac, for either Mac or iOS but can't on either

For iOS, i go in the apple/ios/Monster RPG 2.xcodeproj folder, open it up in xcode ...press the compile for device---i get the error : GenericEffect.cpp:1:10: 'monster2.hpp' file not found (tagged lexical or preprocessor issue) . If i somehow find and add that , it tells me that allegro.h is missing next, if i add that (from the allegro git repository) , the error remains as if nothing was added.

I see the prerequisites listed, but how do i install them into the project so it can be compiled? For example i dowloaded the allegro repository from github, what do i do with it now? Same for BASS and LUA. Do i need to do these steps to compile for Mac/iOS?

Could you tell me how would i go about this, would really appreciate it, as I get the feeling i'm doing it the wrong way...

**Comment by trentg** [comment]
This Wiki page has brief and probably outdated instructions. Try this out and if you need specific help, I'll edit the Wiki and let you know:

http://nooskewl.ca/wiki/index.php/Monster_RPG_2:Building_on_Mac_OS_X

**Comment by trentg** [comment]
Any luck? I will close this issue for now.
